default:
    just --list

# Build & test & check format - what runs in CI
check:
    garnix run --as-branch main

# Build the centralized client Docker image
build_docker_centralized_client:
    nom build .#docker-psyche-centralized-client --out-link nix-results/docker-psyche-centralized-client
    docker load < nix-results/docker-psyche-centralized-client

# Build the solana client Docker image
build_docker_solana_client:
    nom build .#docker-psyche-solana-client --out-link nix-results/docker-psyche-solana-client
    docker load < nix-results/docker-psyche-solana-client

# Build the image for the solana client used for testing
build_docker_solana_test_client:
    nix build .#docker-psyche-solana-test-client --out-link nix-results/docker-psyche-solana-test-client
    docker load < nix-results/docker-psyche-solana-test-client

# Build the image for the solana client used for testing (without Python dependencies)
build_docker_solana_test_client_no_python:
    nix build .#docker-psyche-solana-test-client-no-python --out-link nix-results/docker-psyche-solana-test-client-no-python
    docker load < nix-results/docker-psyche-solana-test-client-no-python
    docker tag psyche-solana-test-client-no-python:latest psyche-solana-test-client:latest

# Build the image for the solana vaidator used for testing
build_docker_solana_test_validator:
    PSYCHE_HOME=$(realpath ..) nix build .#docker-psyche-solana-test-validator --out-link nix-results/docker-psyche-solana-test-validator --impure
    docker load < nix-results/docker-psyche-solana-test-validator
